---
- name: Update and upgrade packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name: "*"
    state: latest

- name: Update the OS
  ansible.builtin.apt:
    upgrade: dist
