---
- name: Install Nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Synchronize webpage files
  become: yes
  ansible.builtin.synchronize:
    src: "{{ WEBPAGE_CODE_SOURCE }}"
    dest: "{{ WEBPAGE_CODE_DESTINATION }}"
    rsync_opts:
      - "--chmod=Du+rwx,Dgo+rx,Fu+rw,Fgo+r"

- name: Apply Nginx template
  template:
    src: "{{ SOURCE_NGINX_CONFIG }}"
    dest: "{{ SITES_AVAILABLE }}"
  notify: Restart nginx server

- name: Set ownership for WEBPAGE_CODE_DESTINATION directory
  become: yes
  ansible.builtin.file:
    path: "{{ WEBPAGE_CODE_DESTINATION }}"
    owner: "{{ ROOT_USER_NAME }}"
    group: "{{ ROOT_USER_GROUP }}"
    recurse: yes

- name: Set permissions for WEBPAGE_CODE_DESTINATION
  become: yes
  ansible.builtin.file:
    path: "{{ WEBPAGE_CODE_DESTINATION }}"
    mode: "u+rwx"
    recurse: yes

- name: Enable new site
  file:
    src: "{{ SITES_AVAILABLE }}"
    dest: "{{ SITES_ENABLED }}"
    state: link
  notify: Restart nginx server

- name: All access to TCP port 80
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: All access to TCP port 443
  ufw:
    rule: allow
    port: 443
    proto: tcp
  notify: Restart nginx server
